### ISSUE TITLE
Simple way to catch db error

### ISSUE THREAD

**Issue by stefanKBL** [avenirer/CodeIgniter-MY_Model#179]
is there a way to catch db error (ex. missing column or something else) from MY_MODEL or do i need to still use the CI syntax, like :
```
$post=$this->post_model->update(...);
if($this->db_error() ) {
...
}
```
Did someone use a best method for use exceptions for db errors ?
thanks

**Comment by salain** [comment]
What would be the point? 
form_validation should be use to validate an update/insert query.

**Comment by stefanKBL** [comment]
yes of course, your are right, form_validation is used before to filter datas and also some business rules.
But the point is just to check if update / insert is success or error, due to another problem than datas quality (ex.timeout, locking...) Because Before answer to the client (CI is here used as an api server), I just need to be sure operation is done. And usually, try / catch for example is a good way. And that's why, i suppose, CI offer the error() method in db class.

**Comment by salain** [comment]
Ok, I don't think you can access the error this way from the query builder. But never the less a write query (update/insert/delete) will return true (or the id) if it is successful and false if it is not. 
So you only need to verify for that. While developing the application CI does give you a detailed error if the problem is in your code.

Does that address your issue ?
